galaxy_info:
  author: oasis_roles
  description: >-
    Disables all port security on network ports attached to devices with a
    given name syntax
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - oasis

dependencies: []
