galaxy_info:
  author: oasis_roles
  description: Provisions an OpenStack Director system
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis
    - openstack
    - osp
    - director

dependencies: []
