galaxy_info:
  author: David Roble
  description: |-
    Configure security groups in OpenStack
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis
    - openstack
    - osp

dependencies: []
