# role tasks
- name: Set platform/version specific variables
  include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: Attach volume to host
  openstack.cloud.server_volume:
    state: present
    cloud: "{{ volume_attach_os_cloud | default(omit, true) }}"
    server: "{{ volume_attach_server }}"
    volume: "{{ item.name }}"
    device: "{{ item.device | default(omit) }}"
  loop: "{{ volume_attach_volumes }}"
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ volume_attach_os_client_config }}"
