osp_director_become: true
osp_director_become_user: root

osp_director_stage: /home/stack
osp_director_named_env: example-dev
osp_director_undercloud:
  stack_user_password: password
  hostname: director.example.com
  cidr: 192.168.10.10/24
  install_ceph_ansible: false
  nameservers:
    - 8.8.8.8
    - 8.8.4.4

osp_director_overcloud:
  domain: example.com
  ceph: "no"
  overcloud_full_image_root_password: secret123

osp_director_templates: null

osp_director_version: ~
