name: Test with Ansible

"on":
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - galaxy.yml
      - AUTHORS
      - .github/labels.yml
      - .github/release-drafter.yml
  pull_request: {}
  schedule:
    - cron: '12 0 * * *'
  release:
    types:
      - published
      - prereleased

jobs:
  collect:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.collection.outputs.tox-envs }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-modules
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade pip
          pip install tox
      - name: collect depenencies
        id: collection
        uses: greg-hellings/tox-list@v1
        with:
          tox-args: --ansible-driver docker --ansible-driver podman

  lint:
    uses: oasis-roles/meta_test/.github/workflows/lint.yml@master

  build:
    needs: collect
    uses: oasis-roles/meta_test/.github/workflows/container_build.yml@master
    with:
      scenarios: "${{ needs.collect.outputs.scenarios }}"

  release:
    needs:  # Only release if the build is good
      - build
      - lint
    if: github.event_name == 'release'
    uses: oasis-roles/meta_test/.github/workflows/release.yml@master
    secrets:
      galaxy_api_key: "${{ secrets.GALAXY_API_KEY }}"
